language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install "Django<1.10"
  - pip install python-coveralls
  - pip install coverage
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
